on:
  push:
    branches: [main, master, dev]
  pull_request:

name: test-mutation.yaml
permissions: write-all

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set badge to NA
        uses: ./.github/actions/push-badge
        with:
          badge-path: inst/badge-na.json
          badge-name: ${{ github.ref_name }}/muttest.json
          commit-message: "chore: set muttest badge to NA"
          return-to: ${{ github.ref_name }}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::jsonlite

      - name: Mutation testing
        id: mutation-testing
        shell: Rscript {0}
        run: |
          pkgload::load_all()

          plan <- plan(
            mutators = c(
              arithmetic_operators(),
              comparison_operators(),
              logical_operators(),
              list(
                negate_condition(),
                remove_negation()
              )
            )
          )
          score <- muttest(plan)

          cat(sprintf("score=%s\n", score), file = Sys.getenv("GITHUB_OUTPUT"), append = TRUE)

      - name: Create badge
        uses: ./.github/actions/create-badge
        with:
          score: ${{ steps.mutation-testing.outputs.score }}

      - name: Update badge with results
        uses: ./.github/actions/push-badge
        with:
          badge-path: .badges/muttest.json
          badge-name: ${{ github.ref_name }}/muttest.json
          commit-message: "chore: update muttest badge"
